// hub.ts (src/config/hub.ts) · updated 10.10.2026 05:50 (Asia/Jerusalem)
// Silitex Hub: departments (from silitex.it job descriptions, 10/10/2026 — names/direct emails added after contract), thread topics, statuses, matching keywords.
export type Dept = { key: string; en: string; he: string; icon: string; email: string; phone: string; site: string; notes: string; keywords: RegExp };
export const SILITEX = { name: "Silitex S.r.l.", hq: "Viale Commercio 25/27, 37044 Cologna Veneta (VR), Italy", plant: "Viale Industria 34, Cologna Veneta (VR)", warehouse: "Viale Industria 26, Cologna Veneta (VR)", domain: "silitex.it", info: "info@silitex.it" };
export const DEPTS: Dept[] = [
  { key: "mgmt", en: "Management", he: "הנהלה", icon: "🏛️", email: SILITEX.info, phone: "+39 0442 411808", site: "HQ", notes: "Agreement, exclusivity, pricing policy, principal report.", keywords: /agreement|contract|exclusiv|distribut|commission|management|direzione|contratto/i },
  { key: "rnd", en: "R&D leadership — doctors & chemical engineers", he: "מו\"פ — כימאים ומהנדסים", icon: "🔬", email: SILITEX.info, phone: "+39 0442 411808", site: "Research center, Viale Commercio 25/27", notes: "Formulation questions, REACH/D4-D5 statements, drop-in replacement protocols.", keywords: /formulat|reach|d4|d5|siloxane|technical question|protocol|laborator|ricerca|r&d/i },
  { key: "lab", en: "Chemical laboratory — engineers & technicians", he: "מעבדה — QC ובדיקות", icon: "🧪", email: SILITEX.info, phone: "+39 0442 411808", site: "Research center", notes: "CoA, lab tests, sample results, TDS/SDS updates.", keywords: /coa|certificate of analysis|sds|msds|tds|test result|sample result|quality|analisi|scheda/i },
  { key: "sales", en: "Sales technicians, agents & representatives", he: "מכירות טכניות וסוכנים", icon: "💼", email: SILITEX.info, phone: "+39 0442 411561", site: "HQ", notes: "Price lists, offers, MOQ, sample kits, customer applications.", keywords: /price|quote|offer|offerta|listino|moq|sample kit|campion|discount/i },
  { key: "backoffice", en: "Back-office sales (Italy)", he: "בק-אופיס מכירות", icon: "🗂️", email: SILITEX.info, phone: "+39 0442 411561", site: "HQ", notes: "Order confirmations, pro-forma, invoices, payment terms. (Open position on silitex.it.)", keywords: /order confirm|proforma|pro-forma|invoice|fattura|payment|pagamento|ordine|p\/?o\b/i },
  { key: "logistics", en: "Purchasing & logistics office / warehouse", he: "רכש ולוגיסטיקה / מחסן", icon: "🚢", email: SILITEX.info, phone: "+39 0442 411561", site: "Warehouse, Viale Industria 26", notes: "Shipment data, packing list, forwarder booking, ADR/IMDG/IATA, EUR.1, ISPM-15. (Open position on silitex.it.)", keywords: /shipment|shipping|spedizion|forwarder|packing|pallet|awb|b\/l|bill of lading|eur\.?1|adr|imdg|iata|container|pickup|ritiro|logistic|warehouse|magazzino|shp-/i },
  { key: "customer", en: "Customer & purchasing service", he: "שירות לקוחות ורכש חו\"ג", icon: "🎧", email: SILITEX.info, phone: "+39 0442 411561", site: "HQ", notes: "Order status, lead times, complaints, raw-material availability.", keywords: /lead time|availability|delivery date|status|complaint|reclamo|disponibil|consegna/i },
  { key: "finance", en: "Marketing & finance", he: "שיווק וכספים", icon: "📈", email: SILITEX.info, phone: "+39 0442 411561", site: "HQ", notes: "Marketing material, certificates for marketing, credit terms, statements.", keywords: /marketing|brochure|catalog|credit|statement|estratto|finance|budget|logo|website/i },
  { key: "plant", en: "Production plant", he: "ייצור", icon: "🏭", email: SILITEX.info, phone: "+39 0442 411561", site: "Plant, Viale Industria 34", notes: "Production slots, batch dates, cargo-ready dates.", keywords: /production|batch|lot\b|lotto|cargo ready|produzione|planning/i },
];
export const TOPICS = ["order", "shipment", "sample", "technical", "quality", "invoice", "contract", "marketing", "other"] as const;
export const TOPIC_HE: Record<string, string> = { order: "הזמנה", shipment: "משלוח", sample: "דגימה", technical: "טכני", quality: "איכות / CoA", invoice: "חשבונית / תשלום", contract: "חוזה", marketing: "שיווק", other: "אחר" };
export const THREAD_STATUS: { key: string; he: string; tone: string }[] = [{ key: "open", he: "פתוח", tone: "blue" }, { key: "waiting_silitex", he: "ממתין ל-Silitex", tone: "amber" }, { key: "waiting_us", he: "ממתין לנו", tone: "red" }, { key: "closed", he: "סגור ✓", tone: "green" }];
export const WAITING_ALERT_DAYS = 2;
export const deptOf = (text: string) => DEPTS.find((d) => d.keywords.test(text))?.key || "customer";
