// build-index.mjs (scripts/build-index.mjs) · updated 09.10.2026 12:30 (Asia/Jerusalem)
// Indexes ALL bundled assets into src/data/search_index.json (one doc per product / offset row / food-grade line / priority / lead / plan). Runs on `npm run build` (prebuild).
import fs from "node:fs";
const rd = (f) => JSON.parse(fs.readFileSync(new URL("../src/data/" + f, import.meta.url), "utf8"));
const docs = [];
for (const p of rd("products.json")) docs.push({ id: p.id, type: "product", title: p.product_name, ref: p.product_name, text: [p.brand_family, p.category_sector, "Applications: " + p.application_field, "Appearance: " + p.appearance, "Active: " + p.active_content_pct + " " + p.active_matter_type, "Viscosity: " + p.viscosity, "Ionicity: " + p.ionicity, "pH: " + p.ph_range, "Solubility: " + p.dilution_solubility, "Features: " + p.key_features, "Certifications: " + p.food_grade_certifications, "INCI: " + p.inci_chemical_name, "Replaces: " + p.dow_corning_offset_benchmark].join(". ") });
const off = rd("offsets.json");
for (const r of off.rows) docs.push({ id: r.category_id, type: "offset", title: r.family, ref: r.silitex_product.split(" - ")[0], text: [r.silitex_product, "INCI: " + r.inci, "Dow Corning / DOWSIL / XIAMETER: " + r.dow_corning, "Kosher: " + r.kosher, "FDA: " + r.fda, "Certs: " + r.eco_certs, ...Object.entries(r.offsets).filter(([, v]) => v !== "N/A").map(([k, v]) => k + ": " + v)].join(". ") });
for (const f of rd("food_grade.json")) docs.push({ id: "FG-" + f.trade_name, type: "food_grade", title: f.trade_name + " (food grade)", ref: f.trade_name, text: ["Composition: " + f.composition, "Kosher: " + f.kosher, "FDA: " + f.fda, "Application: " + f.application, "Dosage: " + f.dosage, "Performance: " + f.performance].join(". ") });
for (const p of rd("priorities.json")) docs.push({ id: "PR-" + p.rank, type: "priority", title: "Priority " + p.rank + ": " + p.family, ref: p.family, text: ["SKUs: " + p.skus, "Specs: " + p.specs, "Israeli targets: " + p.targets, "Use case: " + p.use_case, "Incumbents: " + p.offsets, "Potential: " + p.volume_tons + " t/yr, $" + p.value_usd].join(". ") });
for (const l of rd("leads.json")) docs.push({ id: l.id, type: "lead", title: l.name, ref: l.name, text: [l.industry, l.sub_industry, "Match: " + l.product_match, "Use case: " + l.use_case, "Potential: " + l.volume_tons + " t/yr, $" + l.value_usd, l.tier, "Contact: " + l.contact_role + ", " + l.department, l.recommended_sku ? "Recommended SKU: " + l.recommended_sku : "", l.competitor_offset ? "Replaces: " + l.competitor_offset : "", l.plan_phase ? "Plan: " + l.plan_phase + " — " + l.plan_next_action : "", l.city ? "Location: " + l.city : ""].filter(Boolean).join(". ") });
fs.writeFileSync(new URL("../src/data/search_index.json", import.meta.url), JSON.stringify({ built: new Date().toISOString(), count: docs.length, docs }));
console.log("search index:", docs.length, "docs");
